
-- roles
CREATE TABLE IF NOT EXISTS roles (
	role_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	role_name VARCHAR(100) NOT NULL
);

-- users
CREATE TABLE IF NOT EXISTS users (
	user_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	role_id INT NOT NULL,
	user_name VARCHAR(100) NOT NULL,
	password VARCHAR(255) NOT NULL,
	token VARCHAR(255),
	delete_flg BOOLEAN NOT NULL DEFAULT false,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (role_id) REFERENCES roles(role_id)
);

-- bikes
CREATE TABLE IF NOT EXISTS bikes (
	bike_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	bike_name VARCHAR(100) NOT NULL,
	maker_name VARCHAR(100),
	size INT,
	wheel_base INT,
	bb_shell INT,
	delete_flg BOOLEAN NOT NULL DEFAULT false,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,	
	FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- parts_categories
CREATE TABLE IF NOT EXISTS parts_categories (
	parts_category_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	category_name VARCHAR(100) NOT NULL,
	icon_url VARCHAR(255)
);

-- parts
CREATE TABLE IF NOT EXISTS parts (
	parts_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	bike_id INT NOT NULL,
	parts_category_id INT,
	category_name VARCHAR(100),
	parts_name VARCHAR(100) NOT NULL,
	image_url VARCHAR(255),
	change_date DATETIME NOT NULL,
	price INT,
	delete_flg BOOLEAN NOT NULL DEFAULT false,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (bike_id) REFERENCES bikes(bike_id)
);